title: Postaid 
author: Nirmal Prabhu
email: nirmal.prabhu2019@vitstudent.ac.in
description: > # this means to ignore newlines until "baseurl:"
A prominent problem that is seldom addressed is the post-operative care and maintenance that patients require, especially in fields like Dental Implantology, 
where routine checks are essential. Patients have to travel long distances to the dental clinics to get their implants checked, which can be very inconvenient. 
To solve this dilemma, this project comes up with a chatbot web application to assess post operative status of patients and send reports to doctors. 
There are many health chatbots for diagnosis and a few for post-operative care, but almost none in post-operative care and maintenance in the field of dentistry.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Nirmal-Prabhu

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
